const fs = require('fs');
const path = require('path');

const map = {
  "7-dicas-otimizar-pc-jogos": "7-tips-optimize-pc-gaming",
  "8gb-vs-16gb-ram-jogos": "8gb-vs-16gb-ram-gaming",
  "adrenaline-amd-melhores-configuracoes": "adrenaline-amd-best-settings",
  "agendador-tarefas-otimizacao": "task-scheduler-optimization",
  "air-cooler-vs-water-cooler-pc-gamer": "air-cooler-vs-water-cooler-gaming-pc",
  "ajuste-resolucao-csgo-valorant": "resolution-adjustment-cs2-valorant",
  "alan-wake-2-otimizacao-path-tracing": "alan-wake-2-path-tracing-optimization",
  "alocar-mais-memoria-ram-jogos": "allocate-more-ram-gaming",
  "antivirus-vs-desempenho-jogos": "antivirus-vs-gaming-performance",
  "apex-legends-otimizacao-config-pro": "apex-legends-pro-config-optimization",
  "aprimoramento-ponteiro-mouse-desativar": "disable-enhance-pointer-precision",
  "arquitetura-redes": "network-architecture",
  "assassin-s-creed-mirage-stutter-fix": "assassins-creed-mirage-stutter-fix",
  "assassins-creed-valhalla-stuttering-fix": "assassins-creed-valhalla-stutter-fix",
  "atualizacao-bios": "bios-update",
  "atualizacao-bios-placa-mae-riscos-beneficios": "motherboard-bios-update-risks-benefits",
  "atualizacao-hardware": "hardware-upgrade",
  "atualizacao-software": "software-update",
  "audacity-vs-reaper-edicao-audio": "audacity-vs-reaper-audio-editing",
  "aumentar-fps-csgo": "increase-fps-cs2",
  "aumentar-fps-fivem-gta-rp": "increase-fps-fivem-gta-rp",
  "aumentar-hz-monitor-overclock": "overclock-monitor-hz",
  "autocad-lento-aceleracao-hardware": "autocad-slow-hardware-acceleration",
  "backup-dados": "data-backup",
  "backup-na-nuvem-vs-hd-externo": "cloud-backup-vs-external-hdd",
  "baldur-s-gate-3-vulcan-vs-dx11": "baldurs-gate-3-vulkan-vs-dx11",
  "baldurs-gate-3-otimizacao-act-3": "baldurs-gate-3-act-3-optimization",
  "bateria-viciada-notebook-mito-verdade": "laptop-battery-degradation-myth-truth",
  "bf2042-100-cpu-fix": "battlefield-2042-100-cpu-fix",
  "bluestacks-otimizacao-free-fire-pubg": "bluestacks-optimization-free-fire-pubg",
  "bluestacks-vs-ldplayer-qual-mais-leve": "bluestacks-vs-ldplayer-which-is-lighter",
  "bottleneck-gargalo-cpu-gpu-como-identificar": "bottleneck-cpu-gpu-how-to-identify",
  "brave-vs-chrome-desempenho": "brave-vs-chrome-performance",
  "cadeira-gamer-vs-escritorio-ergonomia": "gaming-chair-vs-office-chair-ergonomics",
  "call-of-duty-warzone-2-otimizacao-fps": "call-of-duty-warzone-2-fps-optimization",
  "capcut-pc-otimizacao-renderizacao": "capcut-pc-render-optimization",
  "choppy-audio-windows-11-fix": "choppy-audio-windows-11-fix",
  "chrome-vs-edge-vs-firefox-ram": "chrome-vs-edge-vs-firefox-ram-usage",
  "cities-skylines-2-otimizacao-fps-mods": "cities-skylines-2-fps-optimization-mods",
  "como-ativar-xmp-docp-bios": "how-to-enable-xmp-docp-bios",
  "como-atualizar-drivers-corretamente": "how-to-update-drivers-correctly",
  "como-aumentar-fps-roblox-pc-fraco": "how-to-increase-fps-roblox-low-end-pc",
  "como-baixar-videos-youtube-4k": "how-to-download-youtube-videos-4k",
  "como-descobrir-temperatura-pc": "how-to-check-pc-temperature",
  "como-escolher-placa-de-video": "how-to-choose-graphics-card",
  "como-escolher-processador-jogos": "how-to-choose-cpu-gaming",
  "como-instalar-ssd-m2-nvme": "how-to-install-m2-nvme-ssd",
  "como-limpar-cache-dns-windows": "how-to-clear-dns-cache-windows",
  "como-limpar-pc-por-dentro": "how-to-clean-pc-internally",
  "como-medir-fps-jogos-msi-afterburner": "how-to-measure-fps-gaming-msi-afterburner",
  "como-montar-pc-gamer-2026": "how-to-build-gaming-pc-2026",
  "como-recuperar-arquivos-deletados-lixeira": "how-to-recover-deleted-files-recycle-bin",
  "como-saber-se-pc-tem-virus": "how-to-know-if-pc-has-virus",
  "como-tirar-print-windows-11": "how-to-take-screenshot-windows-11",
  "computador-reiniciando-sozinho-jogos": "pc-restarting-randomly-gaming",
  "configuracao-backup": "backup-configuration",
  "configuracao-email": "email-configuration",
  "configurar-roteador-wifi-5ghz": "how-to-configure-5ghz-wifi-router",
  "configurar-windows-11-para-jogos": "configure-windows-11-for-gaming",
  "controle-ps5-no-pc-ds4windows": "ps5-controller-on-pc-ds4windows",
  "controle-xbox-nao-conecta-pc-bluetooth": "xbox-controller-not-connecting-pc-bluetooth",
  "correcao-erros": "error-correction",
  "cpu-100-por-cento-windows-11-fix": "cpu-100-percent-windows-11-fix",
  "cpu-z-gpu-z-hwmonitor-como-usar": "cpuz-gpuz-hwmonitor-how-to-use",
  "crashes-jogos-fechando-sozinhos": "game-crashes-closing-randomly-fix",
  "cs2-otimizacao-fps-stuttering-fix": "cs2-fps-optimization-stuttering-fix",
  "cyberpunk-2077-otimizacao-path-tracing": "cyberpunk-2077-path-tracing-optimization",
  "davinci-resolve-lento-otimizacao-playback": "davinci-resolve-slow-playback-optimization",
  "debloat-windows-11-otimizacao-powershell": "debloat-windows-11-powershell-optimization",
  "desativar-aplicativos-segundo-plano-windows": "disable-background-apps-windows",
  "desativar-cortana-windows-11": "disable-cortana-windows-11",
  "desativar-servicos-inuteis-windows-11": "disable-useless-services-windows-11",
  "desativar-telemetria-windows-11": "disable-telemetry-windows-11",
  "desempenho-ssd-nvme-vs-sata-jogos": "nvme-vs-sata-ssd-gaming-performance",
  "desenvolvimento-sistemas": "systems-development",
  "diagnostico-hardware": "hardware-diagnostics",
  "diferenca-entre-ram-vram": "difference-between-ram-and-vram",
  "directx-11-vs-12-qual-melhor-jogos": "directx-11-vs-12-gaming-performance",
  "discord-consumindo-muita-cpu-fix": "discord-high-cpu-usage-fix",
  "disco-100-por-cento-windows-11-solucao": "100-disk-usage-windows-11-fix",
  "dlss-vs-fsr-vs-xess-comparativo": "dlss-vs-fsr-vs-xess-comparison",
  "dota-2-vulkan-vs-dx11-otimizacao": "dota-2-vulkan-vs-dx11-optimization",
  "dr-fone-vs-tenorshare-recuperacao-dados": "drfone-vs-tenorshare-data-recovery",
  "elden-ring-fps-unlock-stutter-fix": "elden-ring-fps-unlock-stutter-fix",
  "emulador-nintendo-switch-yuzu-ryujinx": "nintendo-switch-emulator-yuzu-ryujinx",
  "erro-0xc00007b-jogos-solucao": "error-0xc00007b-games-fix",
  "erro-tela-azul-bsod-como-resolver": "blue-screen-bsod-how-to-fix",
  "escape-from-tarkov-otimizacao-ram-stutter": "escape-from-tarkov-ram-stutter-optimization",
  "euro-truck-simulator-2-otimizacao": "euro-truck-simulator-2-optimization",
  "euro-truck-simulator-2-otimizacao-aa-promods": "euro-truck-simulator-2-promods-aa-optimization",
  "excluir-conta-instagram-definitivamente": "how-to-delete-instagram-account-permanently",
  "exitlag-vale-a-pena-ou-enganacao": "exitlag-worth-it-or-scam",
  "extensoes-produtividade-chrome": "best-chrome-productivity-extensions",
  "fans-fluxo-de-ar-pc-gamer": "pc-case-airflow-fans-setup",
  "firewall-configuracao": "firewall-configuration",
  "formatacao-limpa-windows-11-rufus-gpt": "clean-install-windows-11-rufus-gpt",
  "formatacao-windows": "windows-formatting",
  "formatfactory-vs-handbrake-converter-video": "formatfactory-vs-handbrake-video-converter",
  "fortnite-modo-performance-pc-fraco": "fortnite-performance-mode-low-end-pc",
  "fortnite-texturas-nao-carregam-streaming": "fortnite-textures-not-loading-fix",
  "forza-horizon-5-vram-fix-input-lag": "forza-horizon-5-vram-input-lag-fix",
  "free-fire-pc-fraco-smartgaga": "free-fire-low-end-pc-smartgaga",
  "g-sync-freesync-configuracao-correta": "gsync-freesync-correct-setup",
  "gabinete-gamer-airflow-importancia": "gaming-case-airflow-importance",
  "genshin-impact-fps-unlocker-pc": "genshin-impact-fps-unlocker-pc",
  "genshin-impact-stuttering-fix-pc": "genshin-impact-stutter-fix-pc",
  "geometry-dash-4gb-patch-lag": "geometry-dash-4gb-patch-lag-fix",
  "gestao-pacotes": "package-management",
  "gestao-servicos": "services-management",
  "god-mode-windows-11-ativar": "enable-god-mode-windows-11",
  "god-of-war-pc-memory-leak-fix": "god-of-war-pc-memory-leak-fix",
  "google-chrome-consumo-ram-fix": "google-chrome-high-ram-usage-fix",
  "google-play-games-pc-beta-vale-a-pena": "google-play-games-pc-beta-worth-it",
  "gravação-tela-windows-nativa-dicas": "native-windows-screen-recording-tips",
  "gta-iv-complete-edition-lag-fix": "gta-iv-complete-edition-lag-fix",
  "gta-iv-fix-windows-10-11": "gta-iv-windows-10-11-fix",
  "gta-san-andreas-correcao-grafica": "gta-san-andreas-graphics-fix",
  "gta-v-err-gfx-d3d-init-crash": "gta-v-err-gfx-d3d-init-crash-fix",
  "gta-v-fix-texturas-sumindo": "gta-v-disappearing-textures-fix",
  "gta-v-otimizar-fps-pc-fraco": "gta-v-fps-optimization-low-end-pc",
  "guia-compra-monitores": "monitor-buying-guide",
  "guia-montagem-pc": "pc-building-guide",
  "hard-reset-celular-formatar": "hard-reset-format-smartphone",
  "hard-reset-fones-bluetooth-fix": "hard-reset-bluetooth-headphones-fix",
  "hdmi-2.1-vs-displayport-1.4-diferencas": "hdmi-21-vs-displayport-14-differences",
  "hdr-windows-11-calibracao-jogos": "hdr-windows-11-gaming-calibration",
  "hdr-windows-vale-a-pena-jogos": "hdr-windows-gaming-worth-it",
  "hds-vs-ssd-qual-a-diferenca": "hdd-vs-ssd-whats-the-difference",
  "headset-7.1-real-vs-virtual-vale-a-pena": "real-vs-virtual-71-headset-gaming",
  "hibernacao-vs-suspensao-qual-o-melhor": "hibernation-vs-sleep-mode-windows",
  "hogwarts-legacy-stutter-fix-ram": "hogwarts-legacy-stutter-fix-ram",
  "hollow-knight-stuttering-fix-mod": "hollow-knight-stutter-fix-mod",
  "hyper-v-desempenho-jogos": "hyper-v-impact-gaming-performance",
  "identificacao-phishing": "phishing-identification",
  "importancia-pasta-termica-pc": "thermal-paste-importance-pc",
  "instalacao-drivers": "driver-installation",
  "instalacao-limpa-drivers-nvidia-amd": "clean-driver-install-nvidia-amd",
  "instalacao-windows-11": "windows-11-installation",
  "instalar-apps-android-windows-11": "install-android-apps-windows-11",
  "instalar-impressora-wifi": "install-wifi-printer",
  "is-valorant-dying-state-of-game": "is-valorant-dying-state-of-game",
  "jogos-android-no-pc-melhores-emuladores": "best-android-emulators-for-pc",
  "ldplayer-emulador-leve-pc-fraco": "ldplayer-lightweight-emulator-low-end-pc",
  "league-of-legends-fps-drop-fix": "league-of-legends-fps-drop-fix",
  "league-of-legends-tela-preta-carregamento": "league-of-legends-black-screen-loading-fix",
  "lethal-company-fps-boost-mods": "lethal-company-fps-boost-mods",
  "limitar-fps-rivatuner-nvidia": "limit-fps-rivatuner-nvidia",
  "limpar-cache-navegador-chrome-edge": "clear-browser-cache-chrome-edge",
  "limpar-memoria-ram-windows": "clear-ram-memory-windows",
  "limpeza-computador": "computer-cleaning",
  "limpeza-disco-profunda-arquivos-temporarios": "deep-disk-cleanup-temp-files",
  "limpeza-fisica-pc-gamer": "physical-cleaning-gaming-pc",
  "limpeza-navegadores": "browser-cleaning",
  "limpeza-perifericos-mousepad-teclado": "cleaning-peripherals-mousepad-keyboard",
  "lineage-2-otimizar-pvp-fps": "lineage-2-pvp-fps-optimization",
  "linux-gaming-bazzite-nobara-steam-deck-pc": "linux-gaming-bazzite-nobara-steam-deck",
  "lossless-scaling-frame-generation-fsr-guia": "lossless-scaling-frame-generation-fsr-guide",
  "manutencao-preventiva": "preventive-maintenance",
  "manutencao-preventiva-computador": "computer-preventive-maintenance",
  "melhor-dns-jogos-2026": "best-dns-for-gaming-2026",
  "melhor-dns-para-jogos-google-vs-cloudflare": "best-gaming-dns-google-vs-cloudflare",
  "melhores-drivers-nvidia-antigos": "best-older-nvidia-drivers-performance",
  "melhores-navegadores-custo-beneficio": "best-browsers-performance",
  "memoria-virtual-pagefile-ssd-otimizacao": "virtual-memory-pagefile-ssd-optimization",
  "micro-stuttering-em-jogos-causas": "micro-stuttering-in-games-causes",
  "microsoft-flight-simulator-otimizacao-cache-lod": "msfs-2020-cache-lod-optimization",
  "minecraft-alocar-mais-ram": "allocate-more-ram-minecraft",
  "minecraft-aumentar-fps-fabric-sodium": "increase-minecraft-fps-fabric-sodium",
  "minecraft-lag-fix-optifine-fabric": "minecraft-lag-fix-optifine-fabric",
  "minecraft-lento-como-ganhar-fps": "slow-minecraft-how-to-boost-fps",
  "minecraft-optifine-vs-sodium-fabric": "minecraft-optifine-vs-sodium-fabric",
  "minecraft-shaders-iris-sodium-otimizacao-fps": "minecraft-shaders-iris-sodium-fps-optimization",
  "modo-de-jogo-windows-atikvar-ou-nao": "windows-game-mode-on-or-off",
  "monitor-240hz-360hz-vale-a-pena-ghosting": "240hz-360hz-monitors-worth-it-ghosting",
  "monitor-hz-configuracao-correta": "correct-monitor-refresh-rate-setup",
  "monitor-ips-vs-va-vs-tn-jogos": "ips-vs-va-vs-tn-monitor-gaming",
  "monitor-ultrawide-jogos-competitivos": "ultrawide-monitor-competitive-gaming",
  "monitoramento-sistema": "system-monitoring",
  "monitorar-temperatura-pc": "monitor-pc-temperature",
  "montagem-pc-gamer-erros-comuns": "building-gaming-pc-common-mistakes",
  "mouse-acceleration-raw-accel-guia": "mouse-acceleration-raw-accel-guide",
  "mouse-clique-duplo-falhando-fix": "mouse-double-click-failing-fix",
  "mouse-dpi-polling-rate-ideal": "ideal-mouse-dpi-polling-rate",
  "mouse-otimizacao-windows-precisao": "mouse-precision-optimization-windows",
  "mousepad-speed-vs-control": "speed-vs-control-mousepad-gaming",
  "msi-afterburner-overclock-undervolt-guia": "msi-afterburner-overclock-undervolt-guide",
  "mu-online-reduzir-lag-muvoltris": "mu-online-reduce-lag-guide",
  "notebook-gamer-bateria-otimizacao": "gaming-laptop-battery-optimization",
  "notion-vs-obsidian-produtividade": "notion-vs-obsidian-productivity",
  "nvidia-painel-controle-melhores-configuracoes": "nvidia-control-panel-best-settings",
  "nvidia-refelx-on-vs-boost-diferenca": "nvidia-reflex-on-vs-boost-difference",
  "nvme-vs-sata-vale-a-pena-upgrade": "nvme-vs-sata-upgrade-worth-it",
  "o-que-sao-ai-agents-guia-completo": "what-are-ai-agents-complete-guide",
  "obs-studio-gravacao-replay-buffer-av1": "obs-studio-recording-replay-buffer-av1",
  "obs-studio-melhores-configuracoes-stream": "obs-studio-best-streaming-settings",
  "obs-studio-melhores-configuracoes-stream-2026": "obs-studio-best-streaming-settings-2026",
  "obs-studio-streaming-twitch-youtube-guia-completo": "obs-studio-twitch-youtube-streaming-guide",
  "onde-baixar-planilhas-excel-gratis": "where-to-download-free-excel-templates",
  "otimizacao-jogos-pc": "pc-gaming-optimization",
  "otimizacao-performance": "performance-optimization",
  "otimizacao-registro": "registry-optimization",
  "otimizacao-ssd-windows-11": "windows-11-ssd-optimization",
  "otimizacoes-para-notebook-gamer": "gaming-laptop-optimizations",
  "overclock-gpu-msi-afterburner": "gpu-overclock-msi-afterburner",
  "overclock-processador": "cpu-overclocking",
  "overwatch-2-melhores-configuracoes-fps": "overwatch-2-best-fps-settings",
  "overwatch-2-otimizacao-fps-input-lag-reduce-buffering": "overwatch-2-fps-input-lag-optimization",
  "palworld-otimizacao-server-dlss": "palworld-server-dlss-optimization",
  "pasta-windows-winsxs-gigante-como-limpar": "huge-windows-winsxs-folder-how-to-clean",
  "pc-gamer-barato-custo-beneficio-2026": "budget-gaming-pc-build-2026",
  "pc-lento-formatar-vs-limpar": "slow-pc-format-vs-clean",
  "pc-liga-sem-video-diagnostico": "pc-turns-on-no-display-fix",
  "pcsx2-otimizacao-4k-widescreen-texturas-guia": "pcsx2-4k-widescreen-textures-optimization",
  "perda-de-pacote-packet-loss-fix": "packet-loss-fix-gaming",
  "performance-monitor-v2": "performance-monitor-v2",
  "perifericos-gamer-vale-a-pena": "gaming-peripherals-worth-it",
  "perifericos-gamer-vale-a-pena-marcas": "gaming-peripherals-worth-it-brands",
  "pesquisar-arquivos-windows-mais-rapido": "search-windows-files-faster",
  "phasmophobia-reconhecimento-voz-vr": "phasmophobia-voice-recognition-vr-fix",
  "playnite-launchbox-frontend-organizacao-biblioteca": "playnite-launchbox-game-library-frontend",
  "pobreza-digital-pc-fraco-produtividade": "digital-poverty-low-end-pc-productivity",
  "pos-instalacao-windows-11": "post-installation-windows-11",
  "privacidade-windows-telemetria": "windows-privacy-telemetry",
  "problemas-conexao-wifi-causa-solucao": "wifi-connection-problems-fix",
  "problemas-mouse-gamer-sensor": "gaming-mouse-sensor-issues-fix",
  "processadores-2026-analise": "2026-processors-analysis",
  "programas-essenciais-windows": "essential-windows-programs",
  "project-zomboid-fps-boost": "project-zomboid-fps-boost",
  "protecao-dados-privacidade": "data-protection-privacy",
  "protecao-ransomware": "ransomware-protection",
  "pubg-steam-fix-stuttering-travadas": "pubg-steam-stuttering-fix",
  "qual-melhor-windows-para-jogos": "best-windows-version-for-gaming",
  "rainbow-six-siege-vulkan-fps-configuracao-competitiva": "rainbow-six-siege-vulkan-competitive-settings",
  "re-size-bar-ativar-pc-gamer": "enable-re-size-bar-gaming-pc",
  "recuperacao-dados": "data-recovery",
  "recuperacao-dados-hd-corrompido": "corrupted-hdd-data-recovery",
  "recuperacao-sistema": "system-recovery",
  "red-dead-redemption-2-melhores-configuracoes": "red-dead-redemption-2-best-settings",
  "red-dead-redemption-2-melhores-configuracoes-rdr2": "red-dead-redemption-2-best-settings-rdr2",
  "rede-corporativa": "corporate-network",
  "rede-domestica": "home-network",
  "reduzir-ping-exitlag-noping-dns": "reduce-ping-exitlag-noping-dns",
  "reduzir-ping-jogos-online": "reduce-ping-online-games",
  "reduzir-ping-regedit-cmd-jogos": "reduce-ping-regedit-cmd-gaming",
  "remocao-virus-malware": "virus-malware-removal",
  "remover-bloatware-windows-powershell": "remove-windows-bloatware-powershell",
  "reshade-guia-instalacao-ray-tracing-rtgi-filtros": "reshade-installation-guide-rtgi-filters",
  "resolver-erros-windows": "resolve-windows-errors",
  "retroarch-guia-completo-cores-shaders-crt": "retroarch-complete-guide-shaders-crt",
  "roblox-fix-erro-conexao": "roblox-connection-error-fix",
  "roblox-fps-unlocker-bloat-fix-bloxstrap": "roblox-fps-unlocker-bloxstrap-guide",
  "roblox-fps-unlocker-guia": "roblox-fps-unlocker-guide",
  "roblox-fps-unlocker-tutorial": "roblox-fps-unlocker-tutorial",
  "roblox-tela-branca-travada-fix": "roblox-white-screen-freeze-fix",
  "rocket-league-camera-settings-bakkesmod-air-roll": "rocket-league-camera-settings-bakkesmod",
  "rocket-league-melhores-configuracoes-camera": "rocket-league-best-camera-settings",
  "rodar-llm-local-pc-ollama": "run-local-llm-pc-ollama",
  "rog-ally-legion-go-otimizacao-windows-tdp-guia": "rog-ally-legion-go-windows-tdp-optimization",
  "rpcs3-otimizacao-configuracao-60fps-patches-guia": "rpcs3-60fps-patches-optimization-guide",
  "rtx-4060-vale-a-pena-2026": "rtx-4060-worth-it-2026",
  "rust-otimizacao-fps-pvp-visibility": "rust-fps-pvp-visibility-optimization",
  "saude-bateria-notebook": "laptop-battery-health",
  "segundo-monitor-vertical-configurar": "setup-second-vertical-monitor",
  "seguranca-digital": "digital-security",
  "seguranca-senhas-gerenciadores": "password-security-managers",
  "seguranca-wifi-avancada": "advanced-wifi-security",
  "smart-delivery-xbox-pc-como-funciona": "how-xbox-smart-delivery-works-pc",
  "solucao-problemas-audio": "audio-troubleshooting",
  "solucao-problemas-bluetooth": "bluetooth-troubleshooting",
  "som-espacial-windows-configurar": "configure-windows-spatial-sound",
  "ssd-nvme-vs-sata-jogos": "nvme-vs-sata-ssd-for-gaming",
  "ssd-vs-hd-qual-melhor": "ssd-vs-hdd-which-is-better",
  "ssd-vs-hdd-guia": "ssd-vs-hdd-guide",
  "stardew-valley-mods-lag-fix": "stardew-valley-mods-lag-fix",
  "starfield-otimizacao-dlss-mods": "starfield-dlss-mods-optimization",
  "steam-deck-otimizacao-cryoutilities-protonge-guia": "steam-deck-cryoutilities-protonge-optimization",
  "steam-launch-options-comandos-fps-boost": "steam-launch-options-fps-boost",
  "steam-slow-download-fix": "steam-slow-download-fix",
  "steam-tarda-baixar-lento-fix": "steam-download-slow-fix",
  "streamlabs-vs-obs-qual-usar": "streamlabs-vs-obs-which-to-use",
  "substituicao-ssd": "ssd-replacement",
  "sync-vertical-g-sync-free-sync-explicacao": "vsync-gsync-freesync-explained",
  "taxa-amostragem-audio-44khz-192khz-bug": "audio-sample-rate-44khz-192khz-bug",
  "team-fortress-2-mastercomfig-fps-competitivo": "team-fortress-2-mastercomfig-competitive-fps",
  "teclado-desconfigurado-abnt2-ansi": "keyboard-layout-fix-abnt2-ansi",
  "teclado-mecanico-rapid-trigger-snap-tap": "mechanical-keyboard-rapid-trigger-snap-tap",
  "teclado-mecanico-vs-membrana-qual-o-melhor": "mechanical-vs-membrane-keyboard",
  "teclado-notebook-parou-fix": "laptop-keyboard-stopped-working-fix",
  "teclados-mecanicos-guia": "mechanical-keyboards-guide",
  "teclados-mecanicos-switches-guia": "mechanical-keyboards-switches-guide",
  "tela-azul-memory-management-fix": "bsod-memory-management-fix",
  "termperatura-pc-fan-control-curva": "pc-temperature-fan-control-curve",
  "terraria-tmodloader-64bit-fix": "terraria-tmodloader-64bit-fix",
  "terraria-tmodloader-calamity-fps-fix": "terraria-tmodloader-calamity-fps-fix",
  "testar-fonte-pc-multimetro": "test-pc-power-supply-multimeter",
  "teste-velocidade-internet": "internet-speed-test",
  "the-witcher-3-next-gen-otimizacao-ray-tracing": "the-witcher-3-next-gen-ray-tracing-optimization",
  "the-witcher-3-next-gen-performance": "the-witcher-3-next-gen-performance",
  "tlauncher-viring-falso-positivo": "tlauncher-virus-false-positive",
  "troubleshooting-internet": "internet-troubleshooting",
  "tutorial-discord-instalar-configurar": "discord-install-configure-tutorial",
  "undervolt-cpu-notebook": "laptop-cpu-undervolt",
  "unpark-cpu-cores-performance-jogos": "unpark-cpu-cores-gaming-performance",
  "upgrade-memoria-ram": "ram-memory-upgrade",
  "upgrade-pc-antigo-vale-a-pena": "upgrade-old-pc-worth-it",
  "usb-nao-reconhecido-reset-drivers": "usb-not-recognized-reset-drivers",
  "valorant-fix-van-9003-secure-boot": "valorant-van-9003-secure-boot-fix",
  "valorant-reduzir-input-lag": "valorant-reduce-input-lag",
  "valorant-reduzir-input-lag-fps-boost-config": "valorant-reduce-input-lag-fps-boost",
  "valorant-van-9003-secure-boot-tpm-fix": "valorant-van-9003-tpm-secure-boot-fix",
  "vbs-memory-integrity-performance": "vbs-memory-integrity-performance",
  "vcruntime140-dll-nao-encontrado": "vcruntime140-dll-not-found-fix",
  "verificar-saude-hd-ssd-crystaldiskinfo": "check-hdd-ssd-health-crystaldiskinfo",
  "virtualizacao-vmware": "vmware-virtualization",
  "vita3k-emulador-ps-vita-configuracao-android-pc": "vita3k-ps-vita-emulator-setup-android-pc",
  "vlc-media-player-vs-potplayer": "vlc-media-player-vs-potplayer",
  "vpn-configuracao": "vpn-configuration",
  "vpn-jogos-exitlag-noping-vale-a-pena": "gaming-vpn-exitlag-noping-worth-it",
  "vpn-vale-a-pena-jogos": "vpn-worth-it-for-gaming",
  "water-cooler-vs-air-cooler": "water-cooler-vs-air-cooler-comparison",
  "water-cooler-vs-air-cooler-qual-escolher": "water-cooler-vs-air-cooler-which-to-choose",
  "webcam-piscando-tela-preta-fix": "webcam-flickering-black-screen-fix",
  "wifi-desconectando-sozinho-windows": "wifi-disconnecting-randomly-windows-fix",
  "windows-defender-otimizacao-jogos": "windows-defender-gaming-optimization",
  "windows-sandbox-testar-virus": "windows-sandbox-test-viruses",
  "windows-update-corrigir-erros": "windows-update-fix-errors",
  "winrar-vs-7zip-qual-melhor": "winrar-vs-7zip-which-is-better",
  "xbox-app-nao-baixa-jogos-gamepass": "xbox-app-not-downloading-gamepass-games",
  "xbox-game-bar-desativar-fps-drop": "disable-xbox-game-bar-fps-drop-fix",
  "xbox-game-pass-pc-vale-a-pena": "xbox-game-pass-pc-worth-it",
  "xenia-emulador-xbox-360-red-dead-redemption-60fps": "xenia-xbox-360-emulator-rdr1-60fps",
  "yuzu-ryujinx-otimizacao-zelda-mario-60fps-guia": "yuzu-ryujinx-zelda-mario-60fps-optimization",
  "z-index-css-explicacao": "css-z-index-explained",
  "zonas-mortas-analogico-controle-fix": "controller-analog-deadzones-fix"
};

const guidesDir = path.join(__dirname, 'app', '[locale]', 'guides');
let nextConfigPath = path.join(__dirname, 'next.config.js');

let nextConfigContent = fs.readFileSync(nextConfigPath, 'utf8');
let redirectsToInject = `\n      // ============================================================
      // MASS REDIRECTS: PORTUGUESE GUIDES -> ENGLISH GUIDES
      // ============================================================\n`;

let renamedCount = 0;

for (const [ptSlug, enSlug] of Object.entries(map)) {
  const oldPath = path.join(guidesDir, ptSlug);
  const newPath = path.join(guidesDir, enSlug);
  
  if (fs.existsSync(oldPath)) {
    fs.renameSync(oldPath, newPath);
    renamedCount++;
  }

  // Generate redirect from /guides/ptSlug to /guides/enSlug
  redirectsToInject += `      { source: '/guides/${ptSlug}', destination: '/guides/${enSlug}', permanent: true },\n`;
  
  // Substituir referencias antigas no proprio next.config.js (caso a destination antiga fosse o ptSlug)
  // ex: destination: '/guides/ssd-vs-hd-qual-melhor' -> destination: '/guides/ssd-vs-hdd-guide'
  const regexDestStr = "destination:\\s*['\"`]/guides/" + ptSlug + "['\"`]";
  const regexDest = new RegExp(regexDestStr, 'g');
  nextConfigContent = nextConfigContent.replace(regexDest, "destination: '/guides/" + enSlug + "'");
  
  const regexSourceStr = "source:\\s*['\"`]/guides/" + ptSlug + "['\"`]";
  const regexSource = new RegExp(regexSourceStr, 'g');
  nextConfigContent = nextConfigContent.replace(regexSource, "source: '/guides/" + enSlug + "'");
}

// Inserir os novos redirects no array de redirects no next.config.js
// Encontrar o final do bloco de redirects.
const insertPoint = nextConfigContent.lastIndexOf(']; // END OF REDIRECTS');
if (insertPoint !== -1) {
    // Isso eh apenas um fallback caso tenha um mark especifico, mas o next.config.js do usuario nao tem mark.
} else {
    // Vamos injetar antes do return [ ou logo depois do utimo redirecionamento.
    const lastRedirectMatch = nextConfigContent.match(/permanent:\\s*true\\s*},[\\s]*\\n/g);
    if(lastRedirectMatch) {
        const last = lastRedirectMatch[lastRedirectMatch.length - 1];
        const lastIdx = nextConfigContent.lastIndexOf(last) + last.length;
        nextConfigContent = nextConfigContent.substring(0, lastIdx) + redirectsToInject + nextConfigContent.substring(lastIdx);
    }
}

fs.writeFileSync(nextConfigPath, nextConfigContent, 'utf8');

console.log("Successfully renamed " + renamedCount + " guide folders.");
console.log('Successfully injected redirects to next.config.js.');
