-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. COMPANIES Table
CREATE TABLE IF NOT EXISTS public.companies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    cnpj TEXT,
    plan_type TEXT DEFAULT 'standard', -- standard, pro, enterprise
    max_devices INTEGER DEFAULT 5,
    license_key TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    subscription_status TEXT DEFAULT 'active', -- active, overdue, cancelled
    subscription_end TIMESTAMP WITH TIME ZONE
);

-- 2. COMPANY_USERS Table (Linking Auth Users to Companies)
CREATE TABLE IF NOT EXISTS public.company_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID NOT NULL, -- References auth.users.id (Supabase Auth)
    role TEXT DEFAULT 'viewer', -- owner, admin, viewer
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, user_id)
);

-- 3. DEVICES Table (PCs)
CREATE TABLE IF NOT EXISTS public.devices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    machine_id TEXT NOT NULL, -- Computed Hash from Desktop App
    hostname TEXT,
    os_version TEXT,
    cpu_model TEXT,
    ram_total_gb DECIMAL(10,2),
    disk_serial TEXT,
    mac_address TEXT,
    
    status TEXT DEFAULT 'offline', -- online, offline
    last_heartbeat TIMESTAMP WITH TIME ZONE,
    
    is_license_revoked BOOLEAN DEFAULT FALSE,
    app_version TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, machine_id)
);

-- 4. TELEMETRY_LOGS Table (TimeSeries Data)
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id UUID REFERENCES public.devices(id) ON DELETE CASCADE,
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    
    cpu_usage DECIMAL(5,2),
    ram_usage_percent DECIMAL(5,2),
    disk_usage_percent DECIMAL(5,2),
    boot_time_seconds DECIMAL(10,2),
    
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster querying of telemetry
CREATE INDEX IF NOT EXISTS idx_telemetry_device_time ON public.telemetry_logs (device_id, timestamp DESC);

-- 5. ALERTS Table
CREATE TABLE IF NOT EXISTS public.device_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id UUID REFERENCES public.devices(id) ON DELETE CASCADE,
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    
    type TEXT NOT NULL, -- RAM_HIGH, DISK_FULL, etc
    level TEXT NOT NULL, -- WARNING, CRITICAL
    message TEXT,
    is_resolved BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 6. REMOTE COMMANDS Table
CREATE TABLE IF NOT EXISTS public.remote_commands (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    device_id UUID REFERENCES public.devices(id) ON DELETE CASCADE,
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    create_user_id UUID, -- Who requested the command
    
    command_type TEXT NOT NULL, -- OPTIMIZE_RAM, CLEAN_SYSTEM, UPDATE_POLICY, REMOTE_LOCK
    payload JSONB DEFAULT '{}',
    status TEXT DEFAULT 'pending', -- pending, sent, completed, failed
    
    result_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    executed_at TIMESTAMP WITH TIME ZONE
);

-- Row Level Security (RLS) Policies (Examples)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;

-- Note: In a real deployment, you must create policies that allow access based on company_users table.
-- Example:
-- CREATE POLICY "Users can view devices of their company" ON public.devices
-- FOR SELECT USING (
--   EXISTS (
--     SELECT 1 FROM public.company_users cu
--     WHERE cu.user_id = auth.uid() AND cu.company_id = public.devices.company_id
--   )
-- );
