-- 1. SESSIONS Table (Tracks App Usage Duration)
CREATE TABLE IF NOT EXISTS public.sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    device_id UUID REFERENCES public.devices(id) ON DELETE CASCADE,
    app_version TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_heartbeat_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE,
    duration_seconds INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active', -- active, idle, completed, timeout
    ip_address TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster active session lookups
CREATE INDEX IF NOT EXISTS idx_sessions_device_status ON public.sessions (device_id, status);
CREATE INDEX IF NOT EXISTS idx_sessions_active ON public.sessions (status) WHERE status = 'active';

-- 2. SESSION_EVENTS Table (Detailed Activity Log)
CREATE TABLE IF NOT EXISTS public.session_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
    device_id UUID REFERENCES public.devices(id) ON DELETE CASCADE,
    
    event_type TEXT NOT NULL, -- APP_OPEN, APP_CLOSE, IDLE_START, IDLE_END, ACTIVITY_RESUME
    metadata JSONB DEFAULT '{}',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for analytics
CREATE INDEX IF NOT EXISTS idx_session_events_session ON public.session_events (session_id);

-- 3. UPDATED DEVICES VIEW (Optional helper, but kept within constraints)
-- We don't alter existing tables, but we can ensure devices has a 'last_active_session_id' if we wanted, 
-- but we will stick to using the sessions table for tracking to avoid migration risks.

-- 4. RLS Policies (Basic examples, ensure to refine based on your auth model)
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_events ENABLE ROW LEVEL SECURITY;

-- Allow devices to insert their own sessions (API normally handles this with service_role, 
-- but if using client libs directly:)
-- CREATE POLICY "Devices can insert sessions" ON public.sessions FOR INSERT WITH CHECK (true);
